export const USER_PLAYLIST_GET_REQUEST = 'USER_PLAYLIST_GET_REQUEST';
export const USER_PLAYLIST_GET_SUCCESS = 'USER_PLAYLIST_GET_SUCCESS';
export const USER_PLAYLIST_GET_ERROR = 'USER_PLAYLIST_GET_ERROR';

export const USER_PLAYLIST_CREATE_REQUEST = ' USER_PLAYLIST_CREATE_REQUEST';
export const USER_PLAYLIST_CREATE_SUCCESS = ' USER_PLAYLIST_CREATE_SUCCESS';
export const USER_PLAYLIST_CREATE_ERROR = ' USER_PLAYLIST_CREATE_ERROR';
export const USER_PLAYLIST_CREATE_RESET = ' USER_PLAYLIST_CREATE_RESET';

export const USER_PLAYLIST_EDIT_REQUEST = ' USER_PLAYLIST_EDIT_REQUEST';
export const USER_PLAYLIST_EDIT_SUCCESS = ' USER_PLAYLIST_EDIT_SUCCESS';
export const USER_PLAYLIST_EDIT_ERROR = ' USER_PLAYLIST_EDIT_ERROR';

export const USER_PLAYLIST_DELETE_REQUEST = ' USER_PLAYLIST_DELETE_REQUEST';
export const USER_PLAYLIST_DELETE_SUCCESS = ' USER_PLAYLIST_DELETE_SUCCESS';
export const USER_PLAYLIST_DELETE_ERROR = ' USER_PLAYLIST_DELETE_ERROR';

export const USER_PLAYLIST_FOLLOW_REQUEST = ' USER_PLAYLIST_FOLLOW_REQUEST';
export const USER_PLAYLIST_FOLLOW_SUCCESS = ' USER_PLAYLIST_FOLLOW_SUCCESS';
export const USER_PLAYLIST_FOLLOW_ERROR = ' USER_PLAYLIST_FOLLOW_ERROR';
export const USER_PLAYLIST_SYNC_FOLLOW = 'USER_PLAYLIST_SYNC_FOLLOW';

export const USER_PLAYLIST_SET_CURRENT_PATH = ' USER_PLAYLIST_SET_CURRENT_PATH';

// This are the values of current path.
export const USER_PLAYLIST_PATH_OWN_PLAYLIST = 'ownPlayList';
export const USER_PLAYLIST_PATH_FOLLOW_PLAYLIST = 'followPlayList';
