export const USER_PLAYLIST_GET_REQUEST = 'USER_PLAYLIST_GET_REQUEST';
export const USER_PLAYLIST_GET_SUCCESS = 'USER_PLAYLIST_GET_SUCCESS';
export const USER_PLAYLIST_GET_ERROR = 'USER_PLAYLIST_GET_ERROR';

export const PLAYLIST_GET_REQUEST = 'PLAYLIST_GET_REQUEST';
export const PLAYLIST_GET_SUCCESS = 'PLAYLIST_GET_SUCCESS';
export const PLAYLIST_GET_ERROR = 'PLAYLIST_GET_ERROR';

export const USER_PLAYLIST_CREATE_REQUEST = ' USER_PLAYLIST_CREATE_REQUEST';
export const USER_PLAYLIST_CREATE_SUCCESS = ' USER_PLAYLIST_CREATE_SUCCESS';
export const USER_PLAYLIST_CREATE_ERROR = ' USER_PLAYLIST_CREATE_ERROR';
export const USER_PLAYLIST_CREATE_RESET = ' USER_PLAYLIST_CREATE_RESET';

export const USER_PLAYLIST_EDIT_REQUEST = ' USER_PLAYLIST_EDIT_REQUEST';
export const USER_PLAYLIST_EDIT_SUCCESS = ' USER_PLAYLIST_EDIT_SUCCESS';
export const USER_PLAYLIST_EDIT_ERROR = ' USER_PLAYLIST_EDIT_ERROR';

export const USER_PLAYLIST_DELETE_REQUEST = ' USER_PLAYLIST_DELETE_REQUEST';
export const USER_PLAYLIST_DELETE_SUCCESS = ' USER_PLAYLIST_DELETE_SUCCESS';
export const USER_PLAYLIST_DELETE_ERROR = ' USER_PLAYLIST_DELETE_ERROR';

export const USER_PLAYLIST_FOLLOW_REQUEST = ' USER_PLAYLIST_FOLLOW_REQUEST';
export const USER_PLAYLIST_FOLLOW_SUCCESS = ' USER_PLAYLIST_FOLLOW_SUCCESS';
export const USER_PLAYLIST_FOLLOW_ERROR = ' USER_PLAYLIST_FOLLOW_ERROR';
export const USER_PLAYLIST_SYNC_FOLLOW = 'USER_PLAYLIST_SYNC_FOLLOW';

export const ADD_SONG_TO_PLAYLIST_REQUEST = 'ADD_SONG_TO_PLAYLIST_REQUEST';
export const ADD_SONG_TO_PLAYLIST_SUCCESS = ' ADD_SONG_TO_PLAYLIST_SUCCESS';
export const ADD_SONG_TO_PLAYLIST_ERROR = 'ADD_SONG_TO_PLAYLIST_ERROR';

export const REMOVE_SONG_FROM_PLAYLIST_REQUEST =
  'REMOVE_SONG_FROM_PLAYLIST_REQUEST';
export const REMOVE_SONG_FROM_PLAYLIST_SUCCESS =
  ' REMOVE_SONG_FROM_PLAYLIST_SUCCESS';
export const REMOVE_SONG_FROM_PLAYLIST_ERROR =
  'REMOVE_SONG_FROM_PLAYLIST_ERROR';

export const USER_PLAYLIST_SET_CURRENT_PATH = ' USER_PLAYLIST_SET_CURRENT_PATH';

// This are the values of current path.
export const USER_PLAYLIST_PATH_OWN_PLAYLIST = 'ownPlayList';
export const USER_PLAYLIST_PATH_FOLLOW_PLAYLIST = 'followPlayList';
