export const SEARCH_SONG_REQUEST = 'SEARCH_SONG_REQUEST';
export const SEARCH_SONG_SUCCESS = 'SEARCH_SONG_SUCCESS';
export const SEARCH_SONG_ERROR = 'SEARCH_SONG_ERROR';

export const SEARCH_PLAYLIST_REQUEST = 'SEARCH_PLAYLIST_REQUEST';
export const SEARCH_PLAYLIST_SUCCESS = 'SEARCH_PLAYLIST_SUCCESS';
export const SEARCH_PLAYLIST_ERROR = 'SEARCH_PLAYLIST_ERROR';
