const genres = [
  { genre: 'Classic' },
  { genre: 'Blues' },
  { genre: 'Jazz' },
  { genre: 'R&B' },
  { genre: 'Rock' },
  { genre: 'Soul' },
  { genre: 'Metal' },
  { genre: 'Punk' },
  { genre: 'Country' },
  { genre: 'Funk' },
  { genre: 'Disco' },
  { genre: 'House' },
  { genre: 'Techno' },
  { genre: 'Pop' },
  { genre: 'Ska' },
  { genre: 'Reggae' },
  { genre: 'D&B' },
  { genre: 'Garage' },
  { genre: 'Flamenco' },
  { genre: 'Rap' },
  { genre: 'Salsa' },
  { genre: 'Bachata' },
  { genre: 'Reggeaton' },
  { genre: 'Instrumental' },
  { genre: 'Progressive' },
  { genre: 'B.S.O' },
  { genre: 'Ambient' },
  { genre: 'Dance' },
  { genre: 'EDM' },
  { genre: 'Dubstep' },
  { genre: 'Folk' },
  { genre: 'Indie' },
  { genre: 'Trance' },
  { genre: 'Trap' },
  { genre: 'Others' },
];

module.exports = {
  genres: genres,
};
