export const MY_SONG_GET_REQUEST = 'MY_SONG_GET_REQUEST';
export const MY_SONG_GET_SUCCESS = 'MY_SONG_GET_SUCCESS';
export const MY_SONG_GET_ERROR = 'MY_SONG_GET_ERROR';

export const MY_SONG_UPLOAD_REQUEST = 'MY_SONG_UPLOAD_REQUEST';
export const MY_SONG_UPLOAD_SUCCESS = 'MY_SONG_UPLOAD_SUCCESS';
export const MY_SONG_UPLOAD_ERROR = 'MY_SONG_UPLOAD_ERROR';
export const MY_SONG_UPLOAD_RESET = 'MY_SONG_UPLOAD_RESET';

export const MY_SONG_EDIT_REQUEST = 'MY_SONG_EDIT_REQUEST';
export const MY_SONG_EDIT_SUCCESS = 'MY_SONG_EDIT_SUCCESS';
export const MY_SONG_EDIT_ERROR = 'MY_SONG_EDIT_ERROR';

export const MY_SONG_DELETE_REQUEST = 'MY_SONG_DELETE_REQUEST';
export const MY_SONG_DELETE_SUCCESS = 'MY_SONG_DELETE_SUCCESS';
export const MY_SONG_DELETE_ERROR = 'MY_SONG_DELETE_ERROR';

export const MY_SONG_LIKE_REQUEST = 'MY_SONG_LIKE_REQUEST';
export const MY_SONG_LIKE_SUCCESS = 'MY_SONG_LIKE_SUCCESS';
export const MY_SONG_LIKE_ERROR = 'MY_SONG_LIKE_ERROR';
export const MY_SONG_SYNC_LIKE = 'MY_SONG_SYNC_LIKE';

export const MY_SONG_SET_CURRENT_PATH = 'MY_SONG_SET_CURRENT_PATH';

// This are the values of current path.
export const MY_SONG_PATH_OWN_SONGS = 'ownSongs';
export const MY_SONG_PATH_LIKED_SONGS = 'likedSongs';
