export const PLAYER_PLAY = 'PLAYER_PLAY';
export const PLAYER_CURRENT_INDEX_PLAYLIST = 'PLAYER_CURRENT_INDEX_PLAYLIST';
// export const PLAYER_NEXT = 'PLAYER_NEXT';
// export const PLAYER_PREV = 'PLAYER_PREV';
