export const PLAYER_PLAY = 'PLAYER_PLAY';
export const PLAYER_PLAY_PLAYLIST = 'PLAYER_PLAY_PLAYLIST';
export const PLAYER_NEXT = 'PLAYER_NEXT';
export const PLAYER_PREV = 'PLAYER_PREV';

export const PLAYER_ADD_TO_QUEUE = 'PLAYER_ADD_TO_QUEUE';
export const PLAYER_REORDER_QUEUE = 'PLAYER_REORDER_QUEUE';
export const PLAYER_PLAY_SPECIFIC_SONG_IN_QUEUE =
  'PLAYER_PLAY_SPECIFIC_SONG_IN_QUEUE';

export const PLAYER_SYNC_SONG_DELETE = 'PLAYER_SYNC_SONG_DELETE';
export const PLAYER_SYNC_PLAYLIST_DELETE = 'PLAYER_SYNC_PLAYLIST_DELETE';
export const PLAYER_RESET = 'PLAYER_RESET';

export const PLAYER_ADD_SONG_PLAYED_REQUEST = 'PLAYER_ADD_SONG_PLAYED_REQUEST';
export const PLAYER_ADD_SONG_PLAYED_SUCCESS = 'PLAYER_ADD_SONG_PLAYED_SUCCESS';
export const PLAYER_ADD_SONG_PLAYED_ERROR = 'PLAYER_ADD_SONG_PLAYED_ERROR';
