export const ROUTES = {
  HOME: '/',
  SIGN_UP: '/sign-up',
  LOGIN: '/login',
  RESET_PASSWORD: '/reset-password',
  PROFILE: '/profile',
  SEARCH: '/search',
  LIBRARY: '/library',
  LIBRARY_SONGS: '/library/songs',
  LIBRARY_PLAYLISTS: '/library/playlists',
  SONG_UPLOAD: '/song/upload',
  TOS: '/tos',
  PLAYLIST: '/playlist/:playListId',
  PLAYLIST_WITHOUT_PARAM: '/playlist/',
  USER: '/user/:userId',
  USER_WITHOUT_PARAM: '/user/',
};
