export const GET_TREND_PLAYLIST_REQUEST = 'GET_TREND_PLAYLIST_REQUEST';
export const GET_TREND_PLAYLIST_SUCCESS = 'GET_TREND_PLAYLIST_SUCCESS';
export const GET_TREND_PLAYLIST_ERROR = 'GET_TREND_PLAYLIST_ERROR';

export const GET_TREND_SONG_REQUEST = 'GET_TREND_SONG_REQUEST';
export const GET_TREND_SONG_SUCCESS = 'GET_TREND_SONG_SUCCESS';
export const GET_TREND_SONG_ERROR = 'GET_TREND_SONG_ERROR';

export const GET_TREND_USER_REQUEST = 'GET_TREND_USER_REQUEST';
export const GET_TREND_USER_SUCCESS = 'GET_TREND_USER_SUCCESS';
export const GET_TREND_USER_ERROR = 'GET_TREND_USER_ERROR';

export const GET_TREND_PLAYED_REQUEST = 'GET_TREND_PLAYED_REQUEST';
export const GET_TREND_PLAYED_SUCCESS = 'GET_TREND_PLAYED_SUCCESS';
export const GET_TREND_PLAYED_ERROR = 'GET_TREND_PLAYED_ERROR';
