export const USER_VIEW_GET_REQUEST = 'USER_VIEW_GET_REQUEST';
export const USER_VIEW_GET_SUCCESS = 'USER_VIEW_GET_SUCCESS';
export const USER_VIEW_GET_ERROR = 'USER_VIEW_GET_ERROR';

export const USER_VIEW_GET_SONGS_REQUEST = 'USER_VIEW_GET_SONGS_REQUEST';
export const USER_VIEW_GET_SONGS_SUCCESS = 'USER_VIEW_GET_SONGS_SUCCESS';
export const USER_VIEW_GET_SONGS_ERROR = 'USER_VIEW_GET_SONGS_ERROR';

export const USER_VIEW_GET_PLAYLISTS_REQUEST =
  'USER_VIEW_GET_PLAYLISTS_REQUEST';
export const USER_VIEW_GET_PLAYLISTS_SUCCESS =
  'USER_VIEW_GET_PLAYLISTS_SUCCESS';
export const USER_VIEW_GET_PLAYLISTS_ERROR = 'USER_VIEW_GET_PLAYLISTS_ERROR';
