export const SONG_UPLOAD_REQUEST = 'SONG_UPLOAD_REQUEST';
export const SONG_UPLOAD_SUCCESS = 'SONG_UPLOAD_SUCCESS';
export const SONG_UPLOAD_ERROR = 'SONG_UPLOAD_ERROR';
export const SONG_UPLOAD_RESET = 'SONG_UPLOAD_RESET';

export const SONG_GET_REQUEST = 'SONG_GET_REQUEST';
export const SONG_GET_SUCCESS = 'SONG_GET_SUCCESS';
export const SONG_GET_ERROR = 'SONG_GET_ERROR';

export const SONG_EDIT_REQUEST = 'SONG_EDIT_REQUEST';
export const SONG_EDIT_SUCCESS = 'SONG_EDIT_SUCCESS';
export const SONG_EDIT_ERROR = 'SONG_EDIT_ERROR';

export const SONG_DELETE_REQUEST = 'SONG_DELETE_REQUEST';
export const SONG_DELETE_SUCCESS = 'SONG_DELETE_SUCCESS';
export const SONG_DELETE_ERROR = 'SONG_DELETE_ERROR';
